version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - ${CONFIG_DIR}/redis:/usr/local/etc/redis

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEFAULT_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DEFAULT_MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db

  myhomenew:
    build: .
    ports:
      - 8020:8020
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}:/app/config
    depends_on:
      - db
      - redis

volumes:
  mongodb:
